### PR TITLE
setup for vscode spell check +fixes

### PR DESCRIPTION
**Pull request by chadgauth**
I am just trying to set this up to help in development but started with something simple. Please don't hate me.

### CODE REVIEW

**Comment by FlorianEagox** [comment]
Hate you?!?!?! You're literally amazing and I appreciate the HECK out of other folx wanting to get involved!!! Thanx dawg

**Review by FlorianEagox — APPROVED** [review]
thank you you absolute gigachad. I meant to go back and fix typos in the readme given I just kinda spat it all out and never checked it, but this is good! c:

**Comment by chadgauth** [comment]
Heyya, no problem, I am trying to just get things to run on my mac / windows. I think Mac is a total no go from trying to debug the pip install from requirements. Windows I got a good venv, but I am getting a NumPy error.

Is there a specific python / venv version to get the `weeablind.py` to run or any pre-reqs I might be missing?

**Comment by FlorianEagox** [comment]
Hey there, I'll quickly do a fresh venv reinstall on Linux and Windows and let you know if I forgot something in the requirements. I think i'ts got to do with the pyannote package?

**Comment by FlorianEagox** [comment]
Okay, after doing a clean windows venv, it runs fine, however, you need to run this:
pip install -qq https://github.com/pyannote/pyannote-audio/archive/refs/heads/develop.zip
I tried to incorporate it into .gitignore, but I couldn't figure out how yet.
I am on Python version 3.8.10. I'm not sure what the minimum version you can use is, but some libraries specify Python 3.7 i think?

Also, do you happen to have a discord? I don't mind GH, but it would be easier to talk there and I could share output samples with you there.

**Comment by chadgauth** [comment]
syberdelicwolf

**Pull request merged**
